// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	"context"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc/metadata"

	"github.com/zhufuyi/sponge/pkg/gin/middleware"
	"github.com/zhufuyi/sponge/pkg/logger"

	sysV1 "github.com/Meikwei/aet_sys/api/sys/v1"
	"github.com/Meikwei/aet_sys/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		sysUserMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			sysUserRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewSysUserHandler())
		})
}

func sysUserRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService sysV1.SysUserLogicer) {
	ctxFn := func(c *gin.Context) context.Context {
		md := metadata.New(map[string]string{
			middleware.ContextRequestIDKey: middleware.GCtxRequestID(c),
		})
		return metadata.NewIncomingContext(c.Request.Context(), md)
	}
	sysV1.RegisterSysUserRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		sysV1.WithSysUserLogger(logger.Get()),
		sysV1.WithSysUserRPCResponse(),
		sysV1.WithSysUserWrapCtx(ctxFn),
		sysV1.WithSysUserErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func sysUserMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/sysUser/:id  will take effect
	// c.setGroupPath("/api/v1/sysUser", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/v1/sys_user/create", middleware.Auth())
	//c.setSinglePath("DELETE", "/v1/sys_user/delete/:id", middleware.Auth())
	//c.setSinglePath("POST", "/v1/sys_user/delete/batch", middleware.Auth())
	//c.setSinglePath("PUT", "/v1/sys_user/update/:id", middleware.Auth())
	//c.setSinglePath("GET", "/v1/sys_user/get/:id", middleware.Auth())
	//c.setSinglePath("POST", "/v1/sys_user/getByCondition", middleware.Auth())
	//c.setSinglePath("POST", "/v1/sys_user/listByIDs", middleware.Auth())
	//c.setSinglePath("POST", "/v1/sys_user/listByLastID", middleware.Auth())
	//c.setSinglePath("POST", "/v1/sys_user/list", middleware.Auth())
}
