// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// sysUser business-level rpc error codes.
// the _sysUserNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	_sysUserNO       = 28
	_sysUserName     = "sysUser"
	_sysUserBaseCode = errcode.RCode(_sysUserNO)

	StatusCreateSysUser         = errcode.NewRPCStatus(_sysUserBaseCode+1, "failed to Create "+_sysUserName)
	StatusDeleteByIDSysUser     = errcode.NewRPCStatus(_sysUserBaseCode+2, "failed to DeleteByID "+_sysUserName)
	StatusDeleteByIDsSysUser    = errcode.NewRPCStatus(_sysUserBaseCode+3, "failed to DeleteByIDs "+_sysUserName)
	StatusUpdateByIDSysUser     = errcode.NewRPCStatus(_sysUserBaseCode+4, "failed to UpdateByID "+_sysUserName)
	StatusGetByIDSysUser        = errcode.NewRPCStatus(_sysUserBaseCode+5, "failed to GetByID "+_sysUserName)
	StatusGetByConditionSysUser = errcode.NewRPCStatus(_sysUserBaseCode+6, "failed to GetByCondition "+_sysUserName)
	StatusListByIDsSysUser      = errcode.NewRPCStatus(_sysUserBaseCode+7, "failed to ListByIDs "+_sysUserName)
	StatusListByLastIDSysUser   = errcode.NewRPCStatus(_sysUserBaseCode+8, "failed to ListByLastID "+_sysUserName)
	StatusListSysUser           = errcode.NewRPCStatus(_sysUserBaseCode+9, "failed to List "+_sysUserName)
	// error codes are globally unique, adding 1 to the previous error code
)
