// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// sysRole business-level rpc error codes.
// the _sysRoleNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	_sysRoleNO       = 63
	_sysRoleName     = "sysRole"
	_sysRoleBaseCode = errcode.RCode(_sysRoleNO)

	StatusCreateSysRole         = errcode.NewRPCStatus(_sysRoleBaseCode+1, "failed to Create "+_sysRoleName)
	StatusDeleteByIDSysRole     = errcode.NewRPCStatus(_sysRoleBaseCode+2, "failed to DeleteByID "+_sysRoleName)
	StatusDeleteByIDsSysRole    = errcode.NewRPCStatus(_sysRoleBaseCode+3, "failed to DeleteByIDs "+_sysRoleName)
	StatusUpdateByIDSysRole     = errcode.NewRPCStatus(_sysRoleBaseCode+4, "failed to UpdateByID "+_sysRoleName)
	StatusGetByIDSysRole        = errcode.NewRPCStatus(_sysRoleBaseCode+5, "failed to GetByID "+_sysRoleName)
	StatusGetByConditionSysRole = errcode.NewRPCStatus(_sysRoleBaseCode+6, "failed to GetByCondition "+_sysRoleName)
	StatusListByIDsSysRole      = errcode.NewRPCStatus(_sysRoleBaseCode+7, "failed to ListByIDs "+_sysRoleName)
	StatusListByLastIDSysRole   = errcode.NewRPCStatus(_sysRoleBaseCode+8, "failed to ListByLastID "+_sysRoleName)
	StatusListSysRole           = errcode.NewRPCStatus(_sysRoleBaseCode+9, "failed to List "+_sysRoleName)
	// error codes are globally unique, adding 1 to the previous error code
)
