apiVersion: v1
kind: Service
metadata:
  name: sys-svc
  namespace: sys
spec:
  selector:
    app: sys
  type: ClusterIP
  ports:
    - name: sys-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: sys-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

