// Code generated by https://github.com/zhufuyi/sponge
// Test_service_sysUser_methods is used to test the sysUser api
// Test_service_sysUser_benchmark is used to performance test the sysUser api

package service

import (
	"context"
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"github.com/zhufuyi/sponge/pkg/grpc/benchmark"

	sysV1 "github.com/Meikwei/aet_sys/api/sys/v1"
	"github.com/Meikwei/aet_sys/configs"
	"github.com/Meikwei/aet_sys/internal/config"
)

// Test service sysUser api via grpc client
func Test_service_sysUser_methods(t *testing.T) {
	conn := getRPCClientConnForTest()
	cli := sysV1.NewSysUserClient(conn)
	ctx, _ := context.WithTimeout(context.Background(), time.Second*30)

	tests := []struct {
		name    string
		fn      func() (interface{}, error)
		wantErr bool
	}{

		{
			name: "Create",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.CreateSysUserRequest{
					UserName:     "", // 用户名昵称
					UserNumber:   "", // 用户编号
					UserPassword: "", // 用户密码
					UserPhone:    "", // 用户手机号
					UserAvatar:   "", // 用户头像
					CreateUser:   "", // 创建人
					UpdateUser:   "", // 更新人
				}

				return cli.Create(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "DeleteByID",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.DeleteSysUserByIDRequest{
					Id: 0,
				}

				return cli.DeleteByID(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "DeleteByIDs",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.DeleteSysUserByIDsRequest{
					Ids: nil,
				}

				return cli.DeleteByIDs(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "UpdateByID",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.UpdateSysUserByIDRequest{
					Id:           0,  // 用户ID
					UserName:     "", // 用户名昵称
					UserNumber:   "", // 用户编号
					UserPassword: "", // 用户密码
					UserPhone:    "", // 用户手机号
					UserAvatar:   "", // 用户头像
					CreateUser:   "", // 创建人
					UpdateUser:   "", // 更新人
				}

				return cli.UpdateByID(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "GetByID",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.GetSysUserByIDRequest{
					Id: 0,
				}

				return cli.GetByID(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "GetByCondition",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.GetSysUserByConditionRequest{
					Conditions: nil,
				}

				return cli.GetByCondition(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "ListByIDs",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.ListSysUserByIDsRequest{
					Ids: nil,
				}

				return cli.ListByIDs(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "ListByLastID",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.ListSysUserByLastIDRequest{
					LastID: 0,  // last id
					Limit:  0,  // limit size per page
					Sort:   "", // sort by column name of table, default is -id, the - sign indicates descending order.
				}

				return cli.ListByLastID(ctx, req)
			},
			wantErr: false,
		},

		{
			name: "List",
			fn: func() (interface{}, error) {
				// todo type in the parameters before testing
				req := &sysV1.ListSysUserRequest{
					Params: nil,
				}

				return cli.List(ctx, req)
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.fn()
			if (err != nil) != tt.wantErr {
				t.Errorf("test '%s' error = %v, wantErr %v", tt.name, err, tt.wantErr)
				return
			}
			data, _ := json.MarshalIndent(got, "", "    ")
			fmt.Println(string(data))
		})
	}
}

// performance test service sysUser api, copy the report to
// the browser to view when the pressure test is finished.
func Test_service_sysUser_benchmark(t *testing.T) {
	err := config.Init(configs.Path("sys.yml"))
	if err != nil {
		panic(err)
	}
	if len(config.Get().GrpcClient) == 0 {
		t.Error("grpcClient is not set in sys.yml")
		return
	}
	host := fmt.Sprintf("%s:%d", config.Get().GrpcClient[0].Host, config.Get().GrpcClient[0].Port)
	protoFile := configs.Path("../api/sys/v1/sys_user.proto")
	// If third-party dependencies are missing during the press test,
	// copy them to the project's third_party directory.
	dependentProtoFilePath := []string{
		configs.Path("../third_party"), // third_party directory
		configs.Path(".."),             // Previous level of third_party
	}

	tests := []struct {
		name    string
		fn      func() error
		wantErr bool
	}{

		{
			name: "Create",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.CreateSysUserRequest{
					UserName:     "", // 用户名昵称
					UserNumber:   "", // 用户编号
					UserPassword: "", // 用户密码
					UserPhone:    "", // 用户手机号
					UserAvatar:   "", // 用户头像
					CreateUser:   "", // 创建人
					UpdateUser:   "", // 更新人
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "Create", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "DeleteByID",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.DeleteSysUserByIDRequest{
					Id: 0,
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "DeleteByID", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "DeleteByIDs",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.DeleteSysUserByIDsRequest{
					Ids: nil,
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "DeleteByIDs", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "UpdateByID",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.UpdateSysUserByIDRequest{
					Id:           0,  // 用户ID
					UserName:     "", // 用户名昵称
					UserNumber:   "", // 用户编号
					UserPassword: "", // 用户密码
					UserPhone:    "", // 用户手机号
					UserAvatar:   "", // 用户头像
					CreateUser:   "", // 创建人
					UpdateUser:   "", // 更新人
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "UpdateByID", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "GetByID",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.GetSysUserByIDRequest{
					Id: 0,
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "GetByID", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "GetByCondition",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.GetSysUserByConditionRequest{
					Conditions: nil,
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "GetByCondition", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "ListByIDs",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.ListSysUserByIDsRequest{
					Ids: nil,
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "ListByIDs", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "ListByLastID",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.ListSysUserByLastIDRequest{
					LastID: 0,  // last id
					Limit:  0,  // limit size per page
					Sort:   "", // sort by column name of table, default is -id, the - sign indicates descending order.
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "ListByLastID", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},

		{
			name: "List",
			fn: func() error {
				// todo type in the parameters before benchmark testing
				message := &sysV1.ListSysUserRequest{
					Params: nil,
				}
				total := 1000 // total number of requests

				b, err := benchmark.New(host, protoFile, "List", message, dependentProtoFilePath, total)
				if err != nil {
					return err
				}
				return b.Run()
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.fn()
			if (err != nil) != tt.wantErr {
				t.Errorf("test '%s' error = %v, wantErr %v", tt.name, err, tt.wantErr)
				return
			}
		})
	}
}
